/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vueSwing;

import Interface.IEpreuveDao;
import Interface.IJoueurDao;
import Interface.IMatchDao;
import Interface.ITournoiDao;
import action.JoueurActionController;
import action.MainController;
import action.MatchActionController;
import action.TournoiActionController;
import beans.BeanException;
import beans.EpreuveData;
import beans.Joueur;
import beans.MatchVersion;
import beans.Tournoi;
import dao.DaoException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;

/**
 *
 * @author WalidDev
 */
public class FenetrePrincipal extends javax.swing.JFrame {

    private MainController mainController;
    private Object[][] modelMainTabJoueur;
    private Object[][] modelMainTabTournoi;
    private Object[][] modelMainTabMatchVainqueur;
    private Object[][] modelMainTabMatchFinaliste;
    private Object[][] modelMainTabEpreuve;
    private JoueurActionController joueurActionController;
    private TournoiActionController tournoiActionController;
    private MatchActionController matchActionController;
    private IJoueurDao joueurDao;
    private ITournoiDao tournoiDao;
    private IMatchDao matchDao;
    private IEpreuveDao epreuveDao;

    /**
     * Creates new form FenetrePrincipal
     *
     * @param mainController
     */
    public FenetrePrincipal(MainController mainController) throws BeanException, DaoException {

        initComponents();
        mainController.setMainWindow(this);
        this.mainController = mainController;
        this.joueurDao = mainController.getJoueurDao();
        this.tournoiDao = mainController.getTournoiDao();
        this.matchDao = mainController.getMatchDao();
        this.epreuveDao = mainController.getEpreuveDao();
        this.joueurActionController = new JoueurActionController(mainController, joueurDao);
        this.tournoiActionController = new TournoiActionController(mainController, tournoiDao);
        this.matchActionController = new MatchActionController(mainController, matchDao);

        this.initialisationPanJoueur();
        this.initialisationPanTournoi();
        this.initialisationPanMatch();
        this.initialisationPanEpreuve();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panJoueur = new javax.swing.JPanel();
        btnRefresh = new javax.swing.JButton();
        labAfficher = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textNomSelected = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textPrenomSelected = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        textSexeSelected = new javax.swing.JTextField();
        btnUpdateJoueur = new javax.swing.JButton();
        jScrollMainTab = new javax.swing.JScrollPane();
        mainTabJoueur = new javax.swing.JTable();
        btnDeleteJoueur = new javax.swing.JButton();
        btnAddJoueur = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        comboListRechercheJoueur = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        textRecherche = new javax.swing.JTextField();
        btnRecherche = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        textIdSelected = new javax.swing.JTextField();
        panTournoi = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAjouterTournoi = new javax.swing.JButton();
        btnModifierTournoi = new javax.swing.JButton();
        btnSupprimerTournoi = new javax.swing.JButton();
        textNomTournoiSelected = new javax.swing.JTextField();
        textCodeTournoiSelected = new javax.swing.JTextField();
        jScrollMainTabTournoi = new javax.swing.JScrollPane();
        mainTabTournoi = new javax.swing.JTable();
        labAfficher1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textRechercheTournoi = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        comboListRechercheTournoi = new javax.swing.JComboBox<>();
        btnRechercheTournoi = new javax.swing.JButton();
        btnRefreshTournoi = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        textIdTournoiSelected = new javax.swing.JTextField();
        panMatch = new javax.swing.JPanel();
        jScrollMainTabMatch = new javax.swing.JScrollPane();
        mainTabMatch = new javax.swing.JTable();
        textRechercheMatch = new javax.swing.JTextField();
        comboListRechercheMatch = new javax.swing.JComboBox<>();
        btnRechercheMatch = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        comboListMatchVainqueurFinaliste = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        comboListAnnee = new javax.swing.JComboBox<>();
        comboListType = new javax.swing.JComboBox<>();
        jScrollMainTabMatch1 = new javax.swing.JScrollPane();
        mainTabEpreuve = new javax.swing.JTable();
        btnFiltrerEpreuve = new javax.swing.JButton();
        btnAllEpreuve = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRefresh.setText("Rafraichir");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        labAfficher.setText("Affichage du/des joueur(s) :");

        jLabel6.setText("NOM :");

        jLabel7.setText("PRENOM :");

        jLabel8.setText("Sexe H ou F :");

        btnUpdateJoueur.setText("Modifier Joueur");
        btnUpdateJoueur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateJoueurActionPerformed(evt);
            }
        });

        mainTabJoueur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "NOM", "PRENOM", "SEXE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        mainTabJoueur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainTabJoueurMouseClicked(evt);
            }
        });
        jScrollMainTab.setViewportView(mainTabJoueur);

        btnDeleteJoueur.setText("Supprimer Joueur");
        btnDeleteJoueur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteJoueurActionPerformed(evt);
            }
        });

        btnAddJoueur.setText("Ajouter Joueur");
        btnAddJoueur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddJoueurActionPerformed(evt);
            }
        });

        jLabel1.setText("Recherche  :");

        comboListRechercheJoueur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("dans :");

        btnRecherche.setText("Rechercher");
        btnRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRechercheActionPerformed(evt);
            }
        });

        jLabel12.setText("ID : ");

        javax.swing.GroupLayout panJoueurLayout = new javax.swing.GroupLayout(panJoueur);
        panJoueur.setLayout(panJoueurLayout);
        panJoueurLayout.setHorizontalGroup(
            panJoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panJoueurLayout.createSequentialGroup()
                .addGroup(panJoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panJoueurLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(panJoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panJoueurLayout.createSequentialGroup()
                                .addComponent(jScrollMainTab, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(panJoueurLayout.createSequentialGroup()
                                .addComponent(labAfficher, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textPrenomSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panJoueurLayout.createSequentialGroup()
                                .addGroup(panJoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panJoueurLayout.createSequentialGroup()
                                        .addComponent(btnAddJoueur, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnUpdateJoueur, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panJoueurLayout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(18, 18, 18)
                                        .addComponent(textIdSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(textNomSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(panJoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panJoueurLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panJoueurLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnDeleteJoueur, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(34, 34, 34)
                        .addGroup(panJoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboListRechercheJoueur, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(textRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panJoueurLayout.createSequentialGroup()
                        .addGap(540, 540, 540)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textSexeSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(518, 518, 518))
        );
        panJoueurLayout.setVerticalGroup(
            panJoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panJoueurLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(panJoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(textPrenomSelected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(textNomSelected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(textIdSelected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(textSexeSelected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panJoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddJoueur)
                    .addGroup(panJoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnUpdateJoueur)
                        .addComponent(btnDeleteJoueur)))
                .addGap(28, 28, 28)
                .addGroup(panJoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labAfficher)
                    .addComponent(btnRefresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panJoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panJoueurLayout.createSequentialGroup()
                        .addComponent(jScrollMainTab)
                        .addContainerGap())
                    .addGroup(panJoueurLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(textRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboListRechercheJoueur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(btnRecherche)
                        .addGap(343, 343, 343))))
        );

        labAfficher.getAccessibleContext().setAccessibleName("Afficher les joueurs");

        jTabbedPane1.addTab("Joueur", panJoueur);

        jLabel3.setText("NOM :");

        jLabel4.setText("Code :");

        btnAjouterTournoi.setText("Ajouter Tournoi");
        btnAjouterTournoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterTournoiActionPerformed(evt);
            }
        });

        btnModifierTournoi.setText("Modifier Tournoi");
        btnModifierTournoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierTournoiActionPerformed(evt);
            }
        });

        btnSupprimerTournoi.setText("Supprimer Tournoi");
        btnSupprimerTournoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerTournoiActionPerformed(evt);
            }
        });

        mainTabTournoi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        mainTabTournoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainTabTournoiMouseClicked(evt);
            }
        });
        jScrollMainTabTournoi.setViewportView(mainTabTournoi);

        labAfficher1.setText("Affichage du/des tournoi(s) :");

        jLabel5.setText("Recherche  :");

        jLabel10.setText("dans :");

        comboListRechercheTournoi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnRechercheTournoi.setText("Rechercher");
        btnRechercheTournoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRechercheTournoiActionPerformed(evt);
            }
        });

        btnRefreshTournoi.setText("Rafraichir");
        btnRefreshTournoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshTournoiActionPerformed(evt);
            }
        });

        jLabel19.setText("ID : ");

        javax.swing.GroupLayout panTournoiLayout = new javax.swing.GroupLayout(panTournoi);
        panTournoi.setLayout(panTournoiLayout);
        panTournoiLayout.setHorizontalGroup(
            panTournoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTournoiLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panTournoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollMainTabTournoi, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panTournoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(panTournoiLayout.createSequentialGroup()
                            .addComponent(labAfficher1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRefreshTournoi, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panTournoiLayout.createSequentialGroup()
                            .addGroup(panTournoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panTournoiLayout.createSequentialGroup()
                                    .addComponent(jLabel19)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(textIdTournoiSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panTournoiLayout.createSequentialGroup()
                                    .addComponent(btnAjouterTournoi, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(33, 33, 33)))
                            .addGroup(panTournoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(panTournoiLayout.createSequentialGroup()
                                    .addComponent(textNomTournoiSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textCodeTournoiSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panTournoiLayout.createSequentialGroup()
                                    .addComponent(btnModifierTournoi, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26)
                                    .addComponent(btnSupprimerTournoi, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(65, 65, 65)
                .addGroup(panTournoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panTournoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnRechercheTournoi, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel5)
                    .addComponent(textRechercheTournoi, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboListRechercheTournoi, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        panTournoiLayout.setVerticalGroup(
            panTournoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTournoiLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panTournoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(textIdTournoiSelected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(textCodeTournoiSelected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNomTournoiSelected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panTournoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAjouterTournoi)
                    .addComponent(btnModifierTournoi)
                    .addComponent(btnSupprimerTournoi))
                .addGap(33, 33, 33)
                .addGroup(panTournoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labAfficher1)
                    .addComponent(btnRefreshTournoi))
                .addGap(18, 18, 18)
                .addGroup(panTournoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollMainTabTournoi, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                    .addGroup(panTournoiLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textRechercheTournoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboListRechercheTournoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnRechercheTournoi)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Tournoi", panTournoi);

        mainTabMatch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        mainTabMatch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainTabMatchMouseClicked(evt);
            }
        });
        jScrollMainTabMatch.setViewportView(mainTabMatch);

        comboListRechercheMatch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnRechercheMatch.setText("Rechercher");
        btnRechercheMatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRechercheMatchActionPerformed(evt);
            }
        });

        jLabel11.setText("dans :");

        jLabel9.setText("Recherche  :");

        jLabel13.setText("Liste Joueur vainqueur/finaliste :");

        comboListMatchVainqueurFinaliste.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboListMatchVainqueurFinaliste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboListMatchVainqueurFinalisteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panMatchLayout = new javax.swing.GroupLayout(panMatch);
        panMatch.setLayout(panMatchLayout);
        panMatchLayout.setHorizontalGroup(
            panMatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMatchLayout.createSequentialGroup()
                .addGroup(panMatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panMatchLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollMainTabMatch, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addGroup(panMatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panMatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnRechercheMatch, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel9)
                            .addComponent(textRechercheMatch, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboListRechercheMatch, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panMatchLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(comboListMatchVainqueurFinaliste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        panMatchLayout.setVerticalGroup(
            panMatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMatchLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panMatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(comboListMatchVainqueurFinaliste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panMatchLayout.createSequentialGroup()
                .addGap(21, 79, Short.MAX_VALUE)
                .addGroup(panMatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panMatchLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textRechercheMatch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboListRechercheMatch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnRechercheMatch))
                    .addComponent(jScrollMainTabMatch, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Match", panMatch);

        comboListAnnee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboListType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        mainTabEpreuve.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        mainTabEpreuve.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainTabEpreuveMouseClicked(evt);
            }
        });
        jScrollMainTabMatch1.setViewportView(mainTabEpreuve);

        btnFiltrerEpreuve.setText("Epreuves Filtrés");
        btnFiltrerEpreuve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrerEpreuveActionPerformed(evt);
            }
        });

        btnAllEpreuve.setText("Toutes Epreuves");
        btnAllEpreuve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllEpreuveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollMainTabMatch1, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAllEpreuve)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboListAnnee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboListType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFiltrerEpreuve)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboListType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboListAnnee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFiltrerEpreuve)
                    .addComponent(btnAllEpreuve))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jScrollMainTabMatch1, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Epreuve", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /////////JOUEUR //////////////////////////////////////////////////////////////////////////////////////////////////////////////
    public void initialisationPanJoueur() throws BeanException, DaoException {
        refreshMainTabJoueur();
        this.getMainTabJoueur().setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        this.getComboListRechercheJoueur().setModel(new javax.swing.DefaultComboBoxModel<>(mainController.getHeaderMainTabJoueur()));
    }

    public void refreshMainTabJoueur() throws BeanException, DaoException {
        this.setModelMainTabJoueur(joueurToTab(joueurDao.lister()));
        this.getMainTabJoueur().setModel(new DefaultTableModelPerso(this.getModelMainTabJoueur(), mainController.getHeaderMainTabJoueur()));
    }

    public void refreshFilteredMainTabJoueur() throws BeanException {
        this.setModelMainTabJoueur(joueurToTab(joueurDao.listerRecherche(this.comboListRechercheJoueur.getSelectedItem().toString(), this.textRecherche.getText())));
        this.mainTabJoueur.setModel(new DefaultTableModelPerso(this.getModelMainTabJoueur(), mainController.getHeaderMainTabJoueur()));
    }

    public Object[][] joueurToTab(ArrayList<Joueur> listJoueur) {

        Object[][] data = new Object[listJoueur.size()][4];

        for (int i = 0; i < listJoueur.size(); i++) {

            data[i][0] = listJoueur.get(i).getId();

            data[i][1] = listJoueur.get(i).getNom();

            data[i][2] = listJoueur.get(i).getPrenom();

            data[i][3] = listJoueur.get(i).getSexe();

        }
        return data;
    }

    ///////////JOUEUR LISTENER
    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        try {
            refreshMainTabJoueur();
        } catch (BeanException ex) {
            Logger.getLogger(FenetrePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DaoException ex) {
            Logger.getLogger(FenetrePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void mainTabJoueurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainTabJoueurMouseClicked
        // TODO add your handling code here:
        joueurActionController.ActionMouseClickTabJoueur();
    }//GEN-LAST:event_mainTabJoueurMouseClicked

    private void btnAddJoueurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddJoueurActionPerformed
        try {
            // TODO add your handling code here:
            //actionController.btnAddJoueurActionPerformedController(mainControle,zoneLog,mainTabJoueur, textNomSelected, textPrenomSelected,textSexeSelected);
            joueurActionController.actionAddJoueur();
        } catch (BeanException ex) {
            Logger.getLogger(FenetrePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DaoException ex) {
            Logger.getLogger(FenetrePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddJoueurActionPerformed

    private void btnUpdateJoueurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateJoueurActionPerformed
        try {
            // TODO add your handling code here:
            //actionController.btnUpdateJoueurActionPerformedController(mainController,zoneLog,mainTabJoueur,textIdSelected,textNomSelected, textPrenomSelected,textSexeSelected);
            joueurActionController.actionEditJoueur();
        } catch (BeanException ex) {
            Logger.getLogger(FenetrePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DaoException ex) {
            Logger.getLogger(FenetrePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdateJoueurActionPerformed

    private void btnDeleteJoueurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteJoueurActionPerformed
        try {
            // TODO add your handling code here:
            //actionController.btnDeleteJoueurActionPerformedController(mainController,zoneLog,mainTabJoueur,textIdSelected);
            joueurActionController.actionDeleteJoueur();
        } catch (BeanException ex) {
            Logger.getLogger(FenetrePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DaoException ex) {
            Logger.getLogger(FenetrePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDeleteJoueurActionPerformed

    private void btnRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRechercheActionPerformed
        try {
            // TODO add your handling code here:
            refreshFilteredMainTabJoueur();
        } catch (BeanException ex) {
            Logger.getLogger(FenetrePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRechercheActionPerformed

    /////////TOURNOI //////////////////////////////////////////////////////////////////////////////////////////////////////////////
    public void initialisationPanTournoi() {
        refreshMainTabTournoi();
        this.getMainTabTournoi().setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        this.comboListRechercheTournoi.setModel(new javax.swing.DefaultComboBoxModel<>(mainController.getHeaderMainTabTournoi()));
    }

    public void refreshMainTabTournoi() {
        this.setModelMainTabTournoi(tournoiToTab(tournoiDao.lister()));
        this.getMainTabTournoi().setModel(new DefaultTableModelPerso(this.getModelMainTabTournoi(), mainController.getHeaderMainTabTournoi()));
    }

    public void refreshFilteredMainTabTournoi() {
        this.setModelMainTabTournoi(tournoiToTab(tournoiDao.listerRecherche(this.comboListRechercheTournoi.getSelectedItem().toString(), this.textRechercheTournoi.getText())));
        this.getMainTabTournoi().setModel(new DefaultTableModelPerso(this.getModelMainTabTournoi(), mainController.getHeaderMainTabTournoi()));
    }

    public Object[][] tournoiToTab(ArrayList<Tournoi> listTournoi) {

        Object[][] data = new Object[listTournoi.size()][3];

        for (int i = 0; i < listTournoi.size(); i++) {

            data[i][0] = listTournoi.get(i).getId();

            data[i][1] = listTournoi.get(i).getNom();

            data[i][2] = listTournoi.get(i).getCode();
        }
        return data;
    }

    ///////////Tournoi LISTENER
    private void mainTabTournoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainTabTournoiMouseClicked
        // TODO add your handling code here:
        tournoiActionController.ActionMouseClickTabTournoi();
    }//GEN-LAST:event_mainTabTournoiMouseClicked

    private void btnAjouterTournoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterTournoiActionPerformed
        // TODO add your handling code here:
        tournoiActionController.actionAddTournoi();
    }//GEN-LAST:event_btnAjouterTournoiActionPerformed

    private void btnModifierTournoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierTournoiActionPerformed
        // TODO add your handling code here:
        tournoiActionController.actionEditTournoi();
    }//GEN-LAST:event_btnModifierTournoiActionPerformed

    private void btnSupprimerTournoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerTournoiActionPerformed
        // TODO add your handling code here:
        tournoiActionController.actionDeleteTournoi();
    }//GEN-LAST:event_btnSupprimerTournoiActionPerformed

    private void btnRechercheTournoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRechercheTournoiActionPerformed
        // TODO add your handling code here:
        refreshFilteredMainTabTournoi();
    }//GEN-LAST:event_btnRechercheTournoiActionPerformed

    private void btnRefreshTournoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshTournoiActionPerformed
        // TODO add your handling code here:
        refreshMainTabTournoi();
    }//GEN-LAST:event_btnRefreshTournoiActionPerformed

    /////////MATCH //////////////////////////////////////////////////////////////////////////////////////////////////////////////
    public void initialisationPanMatch() {
        refreshMainTabMatchVainqueur();
        this.getMainTabMatch().setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        this.getComboListRechercheMatch().setModel(new javax.swing.DefaultComboBoxModel<>(mainController.getHeaderMainTabMatchVainqueur()));
        this.getComboListMatchVainqueurFinaliste().setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Vainqueur", "Finaliste"}));
    }

    public void refreshMainTabMatchVainqueur() {
        this.setModelMainTabMatchVainqueur(matchToTab(matchDao.listerMatchVersion("Vainqueur")));
        this.getMainTabMatch().setModel(new DefaultTableModelPerso(this.getModelMainTabMatchVainqueur(), mainController.getHeaderMainTabMatchVainqueur()));
    }

    public void refreshMainTabMatchFinaliste() {
        this.setModelMainTabMatchFinaliste(matchToTab(matchDao.listerMatchVersion("Finaliste")));
        this.getMainTabMatch().setModel(new DefaultTableModelPerso(this.getModelMainTabMatchFinaliste(), mainController.getHeaderMainTabMatchFinaliste()));
    }

    public void refreshFilteredMainTabMatchVainqueur() {
        this.setModelMainTabMatchVainqueur(matchToTab(matchDao.listerRechercheMatchVersion("Vainqueur", this.comboListRechercheMatch.getSelectedItem().toString(), this.textRechercheMatch.getText())));
        this.getMainTabMatch().setModel(new DefaultTableModelPerso(this.getModelMainTabMatchVainqueur(), mainController.getHeaderMainTabMatchVainqueur()));
    }

    public void refreshFilteredMainTabMatchFinaliste() {
        this.setModelMainTabMatchFinaliste(matchToTab(matchDao.listerRechercheMatchVersion("Finaliste", this.comboListRechercheMatch.getSelectedItem().toString(), this.textRechercheMatch.getText())));
        this.getMainTabMatch().setModel(new DefaultTableModelPerso(this.getModelMainTabMatchFinaliste(), mainController.getHeaderMainTabMatchFinaliste()));
    }

    public Object[][] matchToTab(ArrayList<MatchVersion> listMatchVersion) {

        Object[][] data = new Object[listMatchVersion.size()][5];

        for (int i = 0; i < listMatchVersion.size(); i++) {

            data[i][0] = listMatchVersion.get(i).getIdMatch();

            data[i][1] = listMatchVersion.get(i).getIdJoueur();

            data[i][2] = listMatchVersion.get(i).getNom();

            data[i][3] = listMatchVersion.get(i).getPrenom();

            data[i][4] = listMatchVersion.get(i).getSexe();

        }
        return data;
    }

    ///////////MATCH LISTENER
    private void mainTabMatchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainTabMatchMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mainTabMatchMouseClicked

    private void btnRechercheMatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRechercheMatchActionPerformed
        // TODO add your handling code here:
        if (this.comboListMatchVainqueurFinaliste.getSelectedItem().toString().equals("Vainqueur"))
            refreshFilteredMainTabMatchVainqueur();
        else
            refreshFilteredMainTabMatchFinaliste();
    }//GEN-LAST:event_btnRechercheMatchActionPerformed

    private void comboListMatchVainqueurFinalisteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboListMatchVainqueurFinalisteActionPerformed
        // TODO add your handling code here:
        matchActionController.actionComboListMatchVainqueurFinaliste();
    }//GEN-LAST:event_comboListMatchVainqueurFinalisteActionPerformed

/////////Epreuve //////////////////////////////////////////////////////////////////////////////////////////////////////////////
    public void initialisationPanEpreuve() throws BeanException {
        refreshMainTabEpreuve();
        this.getMainTabEpreuve().setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        this.getComboListAnnee().setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019"}));
        this.getComboListType().setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"H", "F"}));
    }

    public void refreshMainTabEpreuve() throws BeanException {
        this.setModelMainTabEpreuve(epreuveToTab(epreuveDao.listerEpreuveData()));
        this.getMainTabEpreuve().setModel(new DefaultTableModelPerso(this.getModelMainTabEpreuve(), mainController.getHeaderMainTabEpreuve()));
    }

    public void refreshFilteredMainTabEpreuve() throws BeanException {
        this.setModelMainTabEpreuve(epreuveToTab(epreuveDao.listerEpreuveDataFiltered(this.comboListAnnee.getSelectedItem().toString(), this.comboListType.getSelectedItem().toString())));
        this.getMainTabEpreuve().setModel(new DefaultTableModelPerso(this.getModelMainTabEpreuve(), mainController.getHeaderMainTabEpreuve()));
    }

    public Object[][] epreuveToTab(ArrayList<EpreuveData> listEpreuve) {

        Object[][] data = new Object[listEpreuve.size()][8];

        for (int i = 0; i < listEpreuve.size(); i++) {

            data[i][0] = listEpreuve.get(i).getEpreuve().getId();
            data[i][1] = listEpreuve.get(i).getEpreuve().getAnnee();
            data[i][2] = listEpreuve.get(i).getEpreuve().getType();
            data[i][3] = listEpreuve.get(i).getMatch().getIdMatch();
            data[i][4] = listEpreuve.get(i).getVainqueur().getNom();
            data[i][5] = listEpreuve.get(i).getVainqueur().getPrenom();
            data[i][6] = listEpreuve.get(i).getFinaliste().getNom();
            data[i][7] = listEpreuve.get(i).getFinaliste().getPrenom();
        }
        return data;
    }

    ///////////EPREUVE LISTENER
    private void mainTabEpreuveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainTabEpreuveMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mainTabEpreuveMouseClicked

    private void btnFiltrerEpreuveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrerEpreuveActionPerformed
        try {
            // TODO add your handling code here:
            refreshFilteredMainTabEpreuve();
        } catch (BeanException ex) {
            Logger.getLogger(FenetrePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnFiltrerEpreuveActionPerformed

    private void btnAllEpreuveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllEpreuveActionPerformed
        try {
            // TODO add your handling code here:
            refreshMainTabEpreuve();
        } catch (BeanException ex) {
            Logger.getLogger(FenetrePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAllEpreuveActionPerformed

    ////////GETTERS AND SETTERS
    public JTable getMainTabJoueur() {
        return mainTabJoueur;
    }

    public void setMainTabJoueur(JTable mainTabJoueur) {
        this.mainTabJoueur = mainTabJoueur;
    }

    public JTable getMainTabTournoi() {
        return mainTabTournoi;
    }

    public void setMainTabTournoi(JTable mainTabTournoi) {
        this.mainTabTournoi = mainTabTournoi;
    }

    public JTextField getTextIdSelected() {
        return textIdSelected;
    }

    public void setTextIdSelected(JTextField textIdSelected) {
        this.textIdSelected = textIdSelected;
    }

    public JTextField getTextNomSelected() {
        return textNomSelected;
    }

    public void setTextNomSelected(JTextField textNomSelected) {
        this.textNomSelected = textNomSelected;
    }

    public JTextField getTextPrenomSelected() {
        return textPrenomSelected;
    }

    public void setTextPrenomSelected(JTextField textPrenomSelected) {
        this.textPrenomSelected = textPrenomSelected;
    }

    public JTextField getTextSexeSelected() {
        return textSexeSelected;
    }

    public void setTextSexeSelected(JTextField textSexeSelected) {
        this.textSexeSelected = textSexeSelected;
    }

    public JComboBox<String> getComboListRechercheJoueur() {
        return comboListRechercheJoueur;
    }

    public void setComboListRechercheJoueur(JComboBox<String> comboListRechercheJoueur) {
        this.comboListRechercheJoueur = comboListRechercheJoueur;
    }

    public JTextField getTextRecherche() {
        return textRecherche;
    }

    public void setTextRecherche(JTextField textRecherche) {
        this.textRecherche = textRecherche;
    }

    public JComboBox<String> getComboListTournoiRecherche() {
        return comboListRechercheTournoi;
    }

    public void setComboListTournoiRecherche(JComboBox<String> comboListTournoiRecherche) {
        this.comboListRechercheTournoi = comboListTournoiRecherche;
    }

    public JTextField getTextCodeTournoiSelected() {
        return textCodeTournoiSelected;
    }

    public void setTextCodeTournoiSelected(JTextField textCodeTournoiSelected) {
        this.textCodeTournoiSelected = textCodeTournoiSelected;
    }

    public JTextField getTextIdTournoiSelected() {
        return textIdTournoiSelected;
    }

    public void setTextIdTournoiSelected(JTextField textIdTournoiSelected) {
        this.textIdTournoiSelected = textIdTournoiSelected;
    }

    public JTextField getTextNomTournoiSelected() {
        return textNomTournoiSelected;
    }

    public void setTextNomTournoiSelected(JTextField textNomTournoiSelected) {
        this.textNomTournoiSelected = textNomTournoiSelected;
    }

    public JTextField getTextRechercheTournoi() {
        return textRechercheTournoi;
    }

    public void setTextRechercheTournoi(JTextField textRechercheTournoi) {
        this.textRechercheTournoi = textRechercheTournoi;
    }

    public Object[][] getModelMainTabJoueur() {
        return modelMainTabJoueur;
    }

    public void setModelMainTabJoueur(Object[][] modelMainTabJoueur) {
        this.modelMainTabJoueur = modelMainTabJoueur;
    }

    public Object[][] getModelMainTabTournoi() {
        return modelMainTabTournoi;
    }

    public void setModelMainTabTournoi(Object[][] modelMainTabTournoi) {
        this.modelMainTabTournoi = modelMainTabTournoi;
    }

    public JTable getMainTabMatch() {
        return mainTabMatch;
    }

    public void setMainTabMatch(JTable mainTabMatch) {
        this.mainTabMatch = mainTabMatch;
    }

    public JComboBox<String> getComboListMatchVainqueurFinaliste() {
        return comboListMatchVainqueurFinaliste;
    }

    public void setComboListMatchVainqueurFinaliste(JComboBox<String> comboListMatchVainqueurFinaliste) {
        this.comboListMatchVainqueurFinaliste = comboListMatchVainqueurFinaliste;
    }

    public JComboBox<String> getComboListRechercheMatch() {
        return comboListRechercheMatch;
    }

    public void setComboListRechercheMatch(JComboBox<String> comboListRechercheMatch) {
        this.comboListRechercheMatch = comboListRechercheMatch;
    }

    public Object[][] getModelMainTabMatchVainqueur() {
        return modelMainTabMatchVainqueur;
    }

    public void setModelMainTabMatchVainqueur(Object[][] modelMainTabMatchVainqueur) {
        this.modelMainTabMatchVainqueur = modelMainTabMatchVainqueur;
    }

    public Object[][] getModelMainTabMatchFinaliste() {
        return modelMainTabMatchFinaliste;
    }

    public void setModelMainTabMatchFinaliste(Object[][] modelMainTabMatchFinaliste) {
        this.modelMainTabMatchFinaliste = modelMainTabMatchFinaliste;
    }

    public IEpreuveDao getEpreuveDao() {
        return epreuveDao;
    }

    public void setEpreuveDao(IEpreuveDao epreuveDao) {
        this.epreuveDao = epreuveDao;
    }

    public JComboBox<String> getComboListAnnee() {
        return comboListAnnee;
    }

    public void setComboListAnnee(JComboBox<String> comboListAnnee) {
        this.comboListAnnee = comboListAnnee;
    }

    public JComboBox<String> getComboListType() {
        return comboListType;
    }

    public void setComboListType(JComboBox<String> comboListType) {
        this.comboListType = comboListType;
    }

    public JTable getMainTabEpreuve() {
        return mainTabEpreuve;
    }

    public void setMainTabEpreuve(JTable mainTabEpreuve) {
        this.mainTabEpreuve = mainTabEpreuve;
    }

    public Object[][] getModelMainTabEpreuve() {
        return modelMainTabEpreuve;
    }

    public void setModelMainTabEpreuve(Object[][] modelMainTabEpreuve) {
        this.modelMainTabEpreuve = modelMainTabEpreuve;
    }
////////DECLARATION COMPOSANT SWING
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddJoueur;
    private javax.swing.JButton btnAjouterTournoi;
    private javax.swing.JButton btnAllEpreuve;
    private javax.swing.JButton btnDeleteJoueur;
    private javax.swing.JButton btnFiltrerEpreuve;
    private javax.swing.JButton btnModifierTournoi;
    private javax.swing.JButton btnRecherche;
    private javax.swing.JButton btnRechercheMatch;
    private javax.swing.JButton btnRechercheTournoi;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRefreshTournoi;
    private javax.swing.JButton btnSupprimerTournoi;
    private javax.swing.JButton btnUpdateJoueur;
    private javax.swing.JComboBox<String> comboListAnnee;
    private javax.swing.JComboBox<String> comboListMatchVainqueurFinaliste;
    private javax.swing.JComboBox<String> comboListRechercheJoueur;
    private javax.swing.JComboBox<String> comboListRechercheMatch;
    private javax.swing.JComboBox<String> comboListRechercheTournoi;
    private javax.swing.JComboBox<String> comboListType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollMainTab;
    private javax.swing.JScrollPane jScrollMainTabMatch;
    private javax.swing.JScrollPane jScrollMainTabMatch1;
    private javax.swing.JScrollPane jScrollMainTabTournoi;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labAfficher;
    private javax.swing.JLabel labAfficher1;
    private javax.swing.JTable mainTabEpreuve;
    private javax.swing.JTable mainTabJoueur;
    private javax.swing.JTable mainTabMatch;
    private javax.swing.JTable mainTabTournoi;
    private javax.swing.JPanel panJoueur;
    private javax.swing.JPanel panMatch;
    private javax.swing.JPanel panTournoi;
    private javax.swing.JTextField textCodeTournoiSelected;
    private javax.swing.JTextField textIdSelected;
    private javax.swing.JTextField textIdTournoiSelected;
    private javax.swing.JTextField textNomSelected;
    private javax.swing.JTextField textNomTournoiSelected;
    private javax.swing.JTextField textPrenomSelected;
    private javax.swing.JTextField textRecherche;
    private javax.swing.JTextField textRechercheMatch;
    private javax.swing.JTextField textRechercheTournoi;
    private javax.swing.JTextField textSexeSelected;
    // End of variables declaration//GEN-END:variables
}
